import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Notion } from "@/lib/notion";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props: { users: Array<any> }) {
  console.log(props.users);
  return (
    <>
      <Head>
        <title>Salit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Hello World!</h1>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const allUsers = await new Notion().getAllUsers();
  return {
    props: {
      users: allUsers,
    },
  };
};
